# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "hitchkick-tfstate"
    key            = "./terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "aws-tf-state"
  }
}
